name: Sync Docs as Code - Confluence
on:
  push:
    branches:
        - main
    paths:
      - 'docs/**'
jobs:
  docs-as-code:
    runs-on: ubuntu-latest
    name: Sync Docs as Code - Confluence
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: docs
      - name: Sync Docs as Code - Confluence
        uses: Bhacaz/docs-as-code-confluence@v3
        with:
          folder: docs
          username: princeofhearts.1989@gmail.com
          password: ATATT3xFfGF0mdFUtXZPajH2wVVmmcp4H_umnUmB0pazoPatwKamy_5KM94CdeZ3RtJclAVphjppZpIeF1XrEsNFTzdzZKVUL_Tcn_atZNngshgR5RW8ZHJHZa-A5mZg5I2eVTiMvnJNfTTttlvo829Tp8LIu5HlNtdPgA4ZGUwZurr_EHs-3FM=273DC72C
          confluence-base-url: https://docasacodetest.atlassian.net/wiki
          space-key: Confluence1
          parent-page-id: 98329
