name: Sync Docs as Code - Confluence
on:
  push:
    branches:
        - main
    paths:
      - 'docs/**'
jobs:
  docs-as-code:
    runs-on: ubuntu-latest
    name: Sync Docs as Code - Confluence
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: docs
      - name: Sync Docs as Code - Confluence
        uses: Bhacaz/docs-as-code-confluence@v3
        with:
          folder: docs
          username: ${{ secrets.CONFLUENCE_USERNAME }}
          password: ${{ secrets.CONFLUENCE_API_TOKEN }}
          confluence-base-url: https://docasacodetest.atlassian.net/wiki
          space-key: space2
          parent-page-id: 491757
